apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://easyshop.letsdeployit.com/api"
  NEXTAUTH_URL: "https://easyshop.letsdeployit.com/"
  NEXTAUTH_SECRET: "fd1fxzmdzdtMIEkWPee6aLiZ1PcIMHwpvdlBYIjLlkU="
  JWT_SECRET: "a8551a0ff27cd9aa9f7646ff6970f6f56033f19e43fa3582a6bb64f3c16acc75"
